spring:
    data:
      mongodb:
        uri: mongodb://mongo1:30001,mongo2:30002,mongo3:30003/pregunta3?replicaSet=miReplicaSet
#        database: pregunta3
#        host: localhost
#        port: 27017
#        repositories:
#          enabled: true

    datasource:
        url: jdbc:mysql://localhost/pregunta3?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        open-in-view: false
        show-sql: true
        hibernate:
            format_sql: true
            ddl-auto: create-drop
server:
    servlet.encoding.charset: UTF-8
    servlet.encoding.force: true
    error:
      include-stacktrace: on-trace-param
      include-exception: true
